FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG AUDIOEXPLORER_DATA_DIR
ENV AUDIOEXPLORER_DATA_DIR=${AUDIOEXPLORER_DATA_DIR}

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY ${AUDIOEXPLORER_DATA_DIR} ./${AUDIOEXPLORER_DATA_DIR}

CMD ["python", "-m", "app.main"]